name: xubuntu-novnc

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: heungno/xubuntu-xvnc@v1
    - name: heungno/xubuntu-xvnc
      run: docker build . --file Dockerfile --tag heungno/xubuntu-xvnc:$(date +%s)
